export const DeptsActionTypes = {
    FETCH_DEPTS_START: 'FETCH_DEPTS_START' as 'FETCH_DEPTS_START',
    FETCH_DEPTS_SUCCESS: 'FETCH_DEPTS_SUCCESS' as 'FETCH_DEPTS_SUCCESS',
    FETCH_DEPTS_FAILURE: 'FETCH_DEPTS_FAILURE' as 'FETCH_DEPTS_FAILURE',
    ADD_DEPT: 'ADD_DEPT' as 'ADD_DEPT',
    DELETE_DEPT: 'DELETE_DEPT' as 'DELETE_DEPT',
    UPDATE_DEPT: 'UPDATE_DEPT' as 'UPDATE_DEPT',
};
