export const DeptsActionTypes = {
    FETCH_DEPTS_START: 'FETCH_DEPTS_START',
    FETCH_DEPTS_SUCCESS: 'FETCH_DEPTS_SUCCESS',
    FETCH_DEPTS_FAILURE: 'FETCH_DEPTS_FAILURE',
    ADD_DEPT: 'ADD_DEPT',
    DELETE_DEPT: 'DELETE_DEPT',
    UPDATE_DEPT: 'UPDATE_DEPT',
};
