sudo: false

language: node_js
cache: yarn

node_js:
    - 12

git:
    depth: 5

install:
    - yarn install --ignore-engines

branches:
    only:
        - develop

after_success:
    - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
